### ISSUE TITLE
concept is not highlighted

### ISSUE THREAD

**Issue by Mechap** [bfrg/vim-cpp-modern#14]
![image](https://user-images.githubusercontent.com/54742369/110142850-e3028a80-7dd6-11eb-9160-6fbd889d022e.png)

**Comment by Mechap** [comment]
![image](https://user-images.githubusercontent.com/54742369/110143985-1eea1f80-7dd8-11eb-8838-f1727c6d0577.png)
consteval and constinit are not highlighted either

**Comment by Mechap** [comment]
![image](https://user-images.githubusercontent.com/54742369/110144993-3e357c80-7dd9-11eb-8d0b-f9e4fd35384b.png)
here is where are implemented c++20 keywords. Should I set something like let g:cpp_no_20 = 0 ?

**Comment by bfrg** [comment]
Which Vim version do you use? I have removed the keywords `concept` and `consteval` since they have been added to the default C++ syntax files on Dec 19, 2019, see vim/vim@95a9dd1ef. I assumed everyone would have at least this Vim version.

**Comment by Mechap** [comment]
I'm using nvim

**Comment by bfrg** [comment]
The C++ syntax file hasn't been updated in almost 4 years in the neovim [repo](https://github.com/neovim/neovim/blob/3fbff98cfd48941ceac086543dd7d6bcdbfb18ab/runtime/syntax/cpp.vim). You need to address this there.

**Comment by Mechap** [comment]
I opted for nvim-treesitter. Thank you though
