### ISSUE TITLE
About the displayed colorscheme

### ISSUE THREAD

**Issue by kchasialis** [bfrg/vim-cpp-modern#15]
Hello, I know this is not an issue or a bug but I really loved the colorscheme displayed on the screenshot and I cannot find it anywhere online. Is it custom?

Can you help me configure my vim colors the same way? 

Thanks in advance.

**Comment by bfrg** [comment]
I have my own version of the `onedark` color scheme. Just download the below file into the `~/.vim/colors/` directory, and then add `colorscheme onedark` to your `vimrc`.

https://gist.github.com/bfrg/dc149d1b797dd65502db38b1d76b5edd

**Comment by kchasialis** [comment]
Thanks!
