### ISSUE TITLE
Hightlighting custom types that have the `_t` postfix

### ISSUE THREAD

**Issue by zoj613** [bfrg/vim-cpp-modern#16]
It would be nice to have this feature where custom types like `mytype_t` could be highlighted.  This is a common pattern in C and helps easily identify non-built in types.
```c
typedef struct {
	...
} custom_t;

int
myfunc(custom_t* a)
{
	...
}
```

Is it possible to have this feature with this package? I am willing to help where I can, although i'm not experienced with vimscript.

**Comment by zoj613** [comment]
Ended up finding a short solution [here](https://stackoverflow.com/a/63463687) for anyone who stumbles across this issue. Closing.

**Comment by bfrg** [comment]
@zoj613 
Instead of the negative lookahead, you can also just match the end of the word:
```vim
syntax match cType "\h\w*_t\>"
```

**Comment by zoj613** [comment]
> ```viml
> syntax match cType "\h\w*_t\>"
> ```

even better. Thanks!
