### ISSUE TITLE
Brace construction in lambdas is highlighting as an error

### ISSUE THREAD

**Issue by jagerman** [bfrg/vim-cpp-modern#20]
Example:
```C++
auto bar1 = int{42};
auto foo = [bar2=int{42}]() { return bar2; };
```
The highlighting on bar1 is fine, but the highlighting on the local lambda capture variable highlights `{` and `}` in the `[bar2=int{42}]` as errors:
![image](https://user-images.githubusercontent.com/4459524/128049631-2d6a8c92-f889-4b29-a3e8-cc324319e1b8.png)

**Comment by bfrg** [comment]
Add the following to your `vimrc`:
```vim
let g:c_no_curly_error = 1
```
See `:help c_no_curly_error` for more details. This option is provided by Vim's default syntax file.

**Comment by jagerman** [comment]
Aha, thank you!
