### ISSUE TITLE
the highlight doesn't change after installing

### ISSUE THREAD

**Issue by Tes-bo** [bfrg/vim-cpp-modern#21]
Hi guys,
I use both plug and git clone to install this plug, but neither works for me, the highlight doesn't change after I restart vim, I'm not sure if I mistook something in the process, I got stuck for all day long lol

**Comment by bfrg** [comment]
Can you open a `cpp` file and then run `:scriptnames` to see if the syntax file has been loaded? Run the following in your terminal:
```bash
$ vim test.cpp +scriptnames
```
What does your `vimrc` look like? Have you enabled syntax highlighting with `syntax on`?

**Comment by Tes-bo** [comment]
Thanks for your reply! 
  I run ` vim mytest.cpp +scriptnams` and it showed the c.vim and cpp.vim are both loaded in my `.vim/plugged/vim-cpp-modern` files. And I've enabled the `syntax on`.

Part of my vimrc is like following, not sure if it will help?
```
syntax on
colorscheme default
set autoindent
set number
set ruler
set backspace=2  " incase cannot delete to the last line
set cursorline  "show the current cursor line
hi CursorLine cterm=underline ctermfg=NONE ctermbg=NONE term=underline guifg=NONE guibg=NONE gui=NONE
```

**Comment by bfrg** [comment]
Can you post a screenshot? And also the output of `:version`.

**Comment by Tes-bo** [comment]
Here is the screenshot of `vim mytest.cpp +scriptnames`
<img width="657" alt="WechatIMG14" src="https://user-images.githubusercontent.com/63994363/130093987-393b39b2-82d0-44c0-aab2-98273e3230b9.png">

And here is the one of `vim :version`
<img width="1533" alt="WechatIMG16" src="https://user-images.githubusercontent.com/63994363/130094200-e21f8e79-cd14-4344-b1a4-ffdaffe572e8.png">

**Comment by bfrg** [comment]
First of all, you need to pick one plugin, either `vim-cpp-enhanced-highlight` or `vim-cpp-modern`, but not both. What I meant, was a screenshot of a C++ file.

**Comment by Tes-bo** [comment]
I removed `vim-cpp-enhanced-highlight` and the screeenshot of my test.CPP files is like following:
![image](https://user-images.githubusercontent.com/63994363/130169204-ede64243-94a9-4701-8d67-41d79d0ade58.png)

**Comment by bfrg** [comment]
The plugin seems to work fine. `shared_ptr`, `pair`, `list`, `allocator` are all highlighted on the left side. What is not highlighted are functions. These should be highlighted with the highlighting group `Function`. You can check the current color settings for `Function` with `:hi Function`.

**Comment by Tes-bo** [comment]
Thanks! And the following is my check result:
```
:hi Function
Function       xxx links to Identifier
```

**Comment by bfrg** [comment]
And what is the output of `:hi Identifier`? Is the `xxx` highlighted in the output of that command?
Have you maybe disabled function highlighting with `let g:cpp_function_highlight = 0`?
While editing a `c` or `cpp` file, can you run `:syn list cUserFunction`?

**Comment by Tes-bo** [comment]
I just set ` let g:cpp_function_highlight = 0 `, now it works fine! Thank you so much mate, appreciate your brilliant work!

**Comment by bfrg** [comment]
That doesn't really make sense that it works after you disabled function highlighting. If you want to enable function highlighting you need to set `g:cpp_function_highlight` to 1 or `true`.

**Comment by Tes-bo** [comment]
yes, I've changed it to 1 already mate
