### ISSUE TITLE
The highlight doesn't work on mac with files named with "*.C" and ".H"

### ISSUE THREAD

**Issue by Tes-bo** [bfrg/vim-cpp-modern#22]
Hi bfrg,

I've found this plug works well on Linux with files named with "*.C" and "*.H", but on mac it doesn't work for these files, may I ask how can I fix it?

**Comment by bfrg** [comment]
When you open a file with file ending `.C` or `.H`, what does `:verbose set filetype?` say? And can you compare it with your Linux machine?

This is my output:
```
  filetype=cpp
        Last set from /usr/share/vim/vim82/filetype.vim line 305
```

**Comment by Tes-bo** [comment]
this is when i open an `.C` file on mac:
```
  filetype=c
        Last set from  /usr/local/share/vim/vim82/autoload/dist/ft.vim line 107
```
and this is when I open an `.C` file on ubuntu:
```
  filetype=cpp
        Last set from /usr/share/vim/vim81/filetype.vim line 293
```

**Comment by bfrg** [comment]
What do you expect `.C` files to be, a C++ or C file? 

The default Vim runtime files suggest that it's a C++ file, but Mac OS developers seem to disagree. You need to ask the maintainer of the Mac version of Vim why they changed it.

This is not a plugin issue.
