### ISSUE TITLE
Template function not highlighted

### ISSUE THREAD

**Issue by Tcholly** [bfrg/vim-cpp-modern#23]
`entity.AddComponent<TagComponent>();` is not highlighted

**Comment by bfrg** [comment]
No, this is not supported and won't be. I have explained it briefly in the [README](https://github.com/bfrg/vim-cpp-modern#difference-to-vim-cpp-enhanced-highlight):

> * User-defined function templates, class names in declarations, and class scopes are not highlighted. Their regex'es are too complicated and slow, and fail too often.

I recommend using a more sophisticated plugin like an LSP client that also implements semantic highlighting or tree-sitter (currently only available in Neovim, AFAIK).
