### ISSUE TITLE
adding modules related keywords

### ISSUE THREAD

**Issue by salimp2009** [bfrg/vim-cpp-modern#33]
hi is possible.
maybe it might sound stupid but is  it possible to add modulessupport like keywords import export. 
Will this also make clangd recognize those as well ?
salim

**Comment by bfrg** [comment]
`import` and `export` should already be highlighted. This is provided by Vim's default syntax file, see: https://github.com/vim/vim/blob/master/runtime/syntax/cpp.vim#L99


>  Will this also make clangd recognize those as well ?

I don't quite understand what you mean. This syntax file has nothing to do with clangd.

**Comment by salimp2009** [comment]
I understood that it has nothing to do with clangd. But do you have modules for syntax tough. I did not see any ? maybe it is not worth it since the C++ lsp servers dont support anyway .
