### ISSUE TITLE
Missing highlight of C++23 integer literals

### ISSUE THREAD

**Issue by jecs** [bfrg/vim-cpp-modern#35]
C++23 introduced the new size suffix `z` or `Z`. More information can be found on the _cppreference_ page on [Integer literals](https://en.cppreference.com/w/cpp/language/integer_literal), under "Syntax". Currently size-suffixed integer literals are not highlighted. Any chance that this could please be added to this plugin?

**Comment by bfrg** [comment]
I think this is so essential that it should be added to Vim's default [cpp syntax file](https://github.com/vim/vim/blob/master/runtime/syntax/cpp.vim). I would suggest opening a feature request in the official [Vim issue tracker](https://github.com/vim/vim/issues).

**Comment by jecs** [comment]
Sure, will do. Thanks!
