### ISSUE TITLE
let g:cpp_no_function_highlight=1 option missing / not working

### ISSUE THREAD

**Issue by kglundgren** [bfrg/vim-cpp-modern#8]
It seems this option has disappeared. It does work when I add it back in myself in the cpp.vim file.

**Comment by bfrg** [comment]
The option didn't disappear. The if-statement was just wrong. You can find it in the `c.vim` syntax file. There's no need to add it to `cpp.vim` since Vim sources all `c.vim` syntax files when a `cpp` file is edited.

**Comment by bfrg** [comment]
I didn't feel like it was necessary to have two separate options for c and cpp, like `c_no_function_highlight` and `cpp_no_function_highlight`. So I kept only one and put it in the file that is always sourced.
